# Generated by Django 4.0.4 on 2022-05-02 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuarances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInsuarance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expire_date', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insuarances.car')),
            ],
        ),
    ]
